/** Popular UK trade-in models — searchable in the form combobox */
export const PHONE_MODELS: readonly string[] = [
  "Apple iPhone 17 Pro Max",
  "Apple iPhone 17 Pro",
  "Apple iPhone 17 Air",
  "Apple iPhone 17 Plus",
  "Apple iPhone 17",
  "Apple iPhone 16 Pro Max",
  "Apple iPhone 16 Pro",
  "Apple iPhone 16 Plus",
  "Apple iPhone 16",
  "Apple iPhone 15 Pro Max",
  "Apple iPhone 15 Pro",
  "Apple iPhone 15 Plus",
  "Apple iPhone 15",
  "Apple iPhone 14 Pro Max",
  "Apple iPhone 14 Pro",
  "Apple iPhone 14 Plus",
  "Apple iPhone 14",
  "Apple iPhone 13 Pro Max",
  "Apple iPhone 13 Pro",
  "Apple iPhone 13 mini",
  "Apple iPhone 13",
  "Apple iPhone 12 Pro Max",
  "Apple iPhone 12 Pro",
  "Apple iPhone 12 mini",
  "Apple iPhone 12",
  "Apple iPhone 11 Pro Max",
  "Apple iPhone 11 Pro",
  "Apple iPhone 11",
  "Apple iPhone SE (3rd gen)",
  "Apple iPhone SE (2nd gen)",
  "Samsung Galaxy S25 Ultra",
  "Samsung Galaxy S25+",
  "Samsung Galaxy S25",
  "Samsung Galaxy S26 Ultra",
  "Samsung Galaxy S26+",
  "Samsung Galaxy S26",
  "Samsung Galaxy S26 FE",
  "Samsung Galaxy S24 Ultra",
  "Samsung Galaxy S24+",
  "Samsung Galaxy S24",
  "Samsung Galaxy S24 FE",
  "Samsung Galaxy S23 Ultra",
  "Samsung Galaxy S23+",
  "Samsung Galaxy S23",
  "Samsung Galaxy S23 FE",
  "Samsung Galaxy S22 Ultra",
  "Samsung Galaxy S22+",
  "Samsung Galaxy S22",
  "Samsung Galaxy S21 Ultra",
  "Samsung Galaxy S21+",
  "Samsung Galaxy S21",
  "Samsung Galaxy S21 FE",
  "Samsung Galaxy Z Fold 7",
  "Samsung Galaxy Z Fold 6",
  "Samsung Galaxy Z Fold 5",
  "Samsung Galaxy Z Fold 4",
  "Samsung Galaxy Z Fold 3",
  "Samsung Galaxy Z Flip 7",
  "Samsung Galaxy Z Flip 6",
  "Samsung Galaxy Z Flip 5",
  "Samsung Galaxy Z Flip 4",
  "Samsung Galaxy Z Flip 3",
  "Samsung Galaxy Note 20 Ultra",
  "Samsung Galaxy Note 20",
  "Samsung Galaxy A55 5G",
  "Samsung Galaxy A35 5G",
  "Google Pixel 9 Pro XL",
  "Google Pixel 9 Pro",
  "Google Pixel 9",
  "Google Pixel 10 Pro Fold",
  "Google Pixel 10 Pro XL",
  "Google Pixel 10 Pro",
  "Google Pixel 10",
  "Google Pixel 10a",
  "Google Pixel 8 Pro",
  "Google Pixel 8",
  "Google Pixel 7 Pro",
  "Google Pixel 7",
  "OnePlus 13",
  "OnePlus 12",
  "Nothing Phone (3)",
  "Nothing Phone (2)",
  "Other / Not listed",
] as const;
